ln2sql_gui/urls.py
from django.conf.urls import url,include
from . import views

app_name='basic'
urlpatterns=[
    url(r'^$',views.index,name='index'),
url(r'^upload/$',views.simple_upload,name='upload')
]

simple_ln2sql/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
url(r'^', include('ln2sql_gui.urls')),

]

ln2sql_gui/models.py
from django.db import models

# Create your models here.

ln2sql_gui/views.py
from django.shortcuts import render,HttpResponse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import ln2sqlmodule as converter
import os

from ln2sqlmodule.ParsingException import ParsingException

DATA_FILE_TYPES = ['sql', 'SQL',]
BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Create your views here.
def index(request):

    return render(request,'ln2sql_gui/index.html',
           {
               'error_message':'',
               'success_message':''
           })


def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        _str = request.POST['message']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        # file_type = filename.url.split('.')[-1]
        # file_type = file_type.lower()
        # if file_type not in DATA_FILE_TYPES:
        #     return render(request, 'ln2sql_gui/index.html', {
        #         'error_message': 'SQL dump file must be in .SQL format',
        #         'success_message': '',
        #         'result': ''
        #     })
        filename="\\database\\" + str(filename)
        try:
            result = converter.getSql(_str,filename)
            return render(request, 'ln2sql_gui/index.html', {
                'error_message': '',
                'success_message': 'Successfully processed',
                'result':result
            })
        except ParsingException:
            return render(request, 'ln2sql_gui/index.html', {
                'error_message': '',
                'success_message': 'uploaded',
                'result': 'Error : No keyword is found'
            })
    return render(request, 'ln2sql_gui/index.html',
                  {
                      'error_message': '',
                      'success_message': '',
                      'result': ''
                       })

ln2sql_gui/templates/ln2sql_gui/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Natural language Processor</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
<!--===============================================================================================-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'ln2sql_gui/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/css/main.css' %}">
<!--===============================================================================================-->

</head>
<body>

	<div class="bg-contact100" style="background-image: url('images/bg-01.jpg');">
		<div class="container-contact100">
			<div class="wrap-contact100">
				<div class="contact100-pic js-tilt" data-tilt>
                    {% load staticfiles %}
					<img src="{% static 'ln2sql_gui/images/images.png' %}" alt="IMG">
					<img src="{% static 'ln2sql_gui/images/images2.jpg' %}" alt="IMG">
				</div>

				<div>
                    <form method="post" action="{% url 'basic:upload' %}" enctype="multipart/form-data">
                        {% csrf_token %}
					<span class="contact100-form-title">
						Natural Langauge Processor
					</span>

                    <P>Specify SQL DUMP FILE</P>
                        {% if error_message %}
                        <p>{{ error_message }}</p>
                        {% endif %}
                    {% if success_message %}
                        <p>{{ success_message }}</p>
                        {% endif %}
					<div class="wrap-input100 validate-input" data-validate = "You need to Upload your SQL Dump">
						<input class="input100" id="file" type="file" name="myfile" placeholder="File">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-file" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "English-like query is required">
						<textarea id="message" class="input100" name="message" placeholder="Enter Your SQL Like Query in English"></textarea>
						<span class="focus-input100"></span>
					</div>



					<div class="container-contact100-form-btn">
						<button class="contact100-form-btn" id="query">
							Convert
						</button>
					</div>
                    </form>
                     <div class="wrap-input100 "><BR>
                         <p><STRONG>RESULT IN SQL </STRONG></p>
						<textarea class="form-control" disabled="">{{ result }}</textarea>
						<span class="focus-input100"></span>
					</div>
				</div>

			</div>
			  
			  <!-- Modal -->
			
		</div>
	</div>


{% load staticfiles %}
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!--===============================================================================================-->
	<script src="{% static 'ln2sql_gui/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'ln2sql_gui/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'ln2sql_gui/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<!-- <script src="vendor/select2/select2.min.js"></script> -->
<!--===============================================================================================-->
	<script src="{% static 'ln2sql_gui/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'ln2sql_gui/js/main.js' %}"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!--===============================================================================================-->
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>
</html>

ln2sql_gui/templates/ln2sql_gui/index2.html
{% extends "ln2sql_gui/layout.html" %}

{% block content %}

<div class="container">
    <h1>Simple Natural language to SQL converter</h1>
<p>How it workd</p>
    <form method="post" action="{% url 'basic:upload' %}" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {% if error_message %}
            <p class="label-info">{{ error_message }}</p>
            {% endif%}
            {% if success_message %}
            <p class="label-info">{{ success_message }}</p>
            {% endif %}
        <div class="form-group">
            <input name="string" class="form-control" placeholder="Enter value to be converted here"/>
        </div>
        <div class="form-group">
            <input class="form-control" type="file" name="myfile"/>
             {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}
        </div>
        </div>



    <button type="submit" class="btn btn-primary">Convert</button>
    </form>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>SQL STATEMENT </h2>
        <p>
            {{ result }}
        </p>

    </div>

</div>

{% endblock %}

ln2sql_gui/templates/ln2sql_gui/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'ln2sql_gui/content/site.css' %}" />
    <script src="{% static 'ln2sql_gui/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'basic:index' %}">Home</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'ln2sql_gui/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'ln2sql_gui/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'ln2sql_gui/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>